[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
graph_of_humanity = "4P5gqBYPRYjca3tQwHiLjKuHmqY9ZoTGVj77tLQNri8T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/tanmay-munjal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "VRFzZoJdhFWL8rkvu87LpKM3RbcVezpMEc6X5GVDr7y"
program = "vrf.so"
